-- insert countries
INSERT INTO `countries` (`code`, `name`) VALUES ('AFG', 'Afghanistan');
INSERT INTO `countries` (`code`, `name`) VALUES ('SAF', 'South Africa');
INSERT INTO `countries` (`code`, `name`) VALUES ('ALB', 'Albania');
INSERT INTO `countries` (`code`, `name`) VALUES ('ALG', 'Algeria');
INSERT INTO `countries` (`code`, `name`) VALUES ('GER', 'Germany');
INSERT INTO `countries` (`code`, `name`) VALUES ('AND', 'Andorra');
INSERT INTO `countries` (`code`, `name`) VALUES ('ANG', 'Angola');
INSERT INTO `countries` (`code`, `name`) VALUES ('ANT', 'Antigua And Barbuda');
INSERT INTO `countries` (`code`, `name`) VALUES ('SAR', 'Saudi Arabia');
INSERT INTO `countries` (`code`, `name`) VALUES ('ARG', 'Argentina');
INSERT INTO `countries` (`code`, `name`) VALUES ('ARM', 'Armenia');
INSERT INTO `countries` (`code`, `name`) VALUES ('ARU', 'Aruba');
INSERT INTO `countries` (`code`, `name`) VALUES ('AUS', 'Australia');
INSERT INTO `countries` (`code`, `name`) VALUES ('AUT', 'Austria');
INSERT INTO `countries` (`code`, `name`) VALUES ('AZE', 'Azerbaijan');
INSERT INTO `countries` (`code`, `name`) VALUES ('BAH', 'Bahamas');
INSERT INTO `countries` (`code`, `name`) VALUES ('BAR', 'Bahrain');
INSERT INTO `countries` (`code`, `name`) VALUES ('BAN', 'Bangladesh');
INSERT INTO `countries` (`code`, `name`) VALUES ('BAB', 'Barbados');
INSERT INTO `countries` (`code`, `name`) VALUES ('BEL', 'Belarus');
INSERT INTO `countries` (`code`, `name`) VALUES ('BLG', 'Belgium');
INSERT INTO `countries` (`code`, `name`) VALUES ('BLZ', 'Belize');
INSERT INTO `countries` (`code`, `name`) VALUES ('BNN', 'Benin');
INSERT INTO `countries` (`code`, `name`) VALUES ('BER', 'Bermuda');
INSERT INTO `countries` (`code`, `name`) VALUES ('BHU', 'Bhutan');
INSERT INTO `countries` (`code`, `name`) VALUES ('BOL', 'Bolivia');
INSERT INTO `countries` (`code`, `name`) VALUES ('BSH', 'Bosnia And Herzegovina');
INSERT INTO `countries` (`code`, `name`) VALUES ('BOT', 'Botswana');
INSERT INTO `countries` (`code`, `name`) VALUES ('BRA', 'Brazil');
INSERT INTO `countries` (`code`, `name`) VALUES ('BRU', 'Brunei Darussalam');
INSERT INTO `countries` (`code`, `name`) VALUES ('BUL', 'Bulgaria');
INSERT INTO `countries` (`code`, `name`) VALUES ('BUR', 'Burkina Faso');
INSERT INTO `countries` (`code`, `name`) VALUES ('BRN', 'Burundi');
INSERT INTO `countries` (`code`, `name`) VALUES ('CAY', 'Cayman Islands');
INSERT INTO `countries` (`code`, `name`) VALUES ('CAM', 'Cambodia');
INSERT INTO `countries` (`code`, `name`) VALUES ('CMR', 'Cameroon');
INSERT INTO `countries` (`code`, `name`) VALUES ('CAN', 'Canada');
INSERT INTO `countries` (`code`, `name`) VALUES ('CAV', 'Cape Verde');
INSERT INTO `countries` (`code`, `name`) VALUES ('CAR', 'Central African Republic');
INSERT INTO `countries` (`code`, `name`) VALUES ('CHI', 'Chile');
INSERT INTO `countries` (`code`, `name`) VALUES ('PRC', 'People`s Republic Of China');
INSERT INTO `countries` (`code`, `name`) VALUES ('CYS', 'Cyprus');
INSERT INTO `countries` (`code`, `name`) VALUES ('COL', 'Colombia');
INSERT INTO `countries` (`code`, `name`) VALUES ('COM', 'Comoros');
INSERT INTO `countries` (`code`, `name`) VALUES ('CON', 'Congo');
INSERT INTO `countries` (`code`, `name`) VALUES ('DRC', 'Democratic Republic Of The Congo');
INSERT INTO `countries` (`code`, `name`) VALUES ('COO', 'Cook Islands');
INSERT INTO `countries` (`code`, `name`) VALUES ('ROK', 'Republic Of Korea');
INSERT INTO `countries` (`code`, `name`) VALUES ('COS', 'Costa Rica');
INSERT INTO `countries` (`code`, `name`) VALUES ('COT', 'Côte D`ivoire');
INSERT INTO `countries` (`code`, `name`) VALUES ('CRO', 'Croatia');
INSERT INTO `countries` (`code`, `name`) VALUES ('CUB', 'Cuba');
INSERT INTO `countries` (`code`, `name`) VALUES ('DEN', 'Denmark');
INSERT INTO `countries` (`code`, `name`) VALUES ('DJI', 'Djibouti');
INSERT INTO `countries` (`code`, `name`) VALUES ('DMR', 'Dominican Republic');
INSERT INTO `countries` (`code`, `name`) VALUES ('DOM', 'Dominique');
INSERT INTO `countries` (`code`, `name`) VALUES ('EGY', 'Egypt');
INSERT INTO `countries` (`code`, `name`) VALUES ('ELS', 'El Salvador');
INSERT INTO `countries` (`code`, `name`) VALUES ('UAE', 'United Arab Emirates');
INSERT INTO `countries` (`code`, `name`) VALUES ('ECU', 'Ecuador');
INSERT INTO `countries` (`code`, `name`) VALUES ('ERI', 'Eritrea');
INSERT INTO `countries` (`code`, `name`) VALUES ('SPN', 'Spain');
INSERT INTO `countries` (`code`, `name`) VALUES ('EST', 'Estonia');
INSERT INTO `countries` (`code`, `name`) VALUES ('USA', 'United States Of America');
INSERT INTO `countries` (`code`, `name`) VALUES ('ETH', 'Ethiopia');
INSERT INTO `countries` (`code`, `name`) VALUES ('MAC', 'The Former Yugoslav Republic Of Macedonia');
INSERT INTO `countries` (`code`, `name`) VALUES ('FIJ', 'Fiji');
INSERT INTO `countries` (`code`, `name`) VALUES ('FIN', 'Finland');
INSERT INTO `countries` (`code`, `name`) VALUES ('FRA', 'France');
INSERT INTO `countries` (`code`, `name`) VALUES ('GAB', 'Gabon');
INSERT INTO `countries` (`code`, `name`) VALUES ('GAM', 'Gambia');
INSERT INTO `countries` (`code`, `name`) VALUES ('GEO', 'Georgia');
INSERT INTO `countries` (`code`, `name`) VALUES ('GHA', 'Ghana');
INSERT INTO `countries` (`code`, `name`) VALUES ('GBR', 'Great Britain');
INSERT INTO `countries` (`code`, `name`) VALUES ('GRE', 'Greece');
INSERT INTO `countries` (`code`, `name`) VALUES ('GRN', 'Grenada');
INSERT INTO `countries` (`code`, `name`) VALUES ('GUA', 'Guam');
INSERT INTO `countries` (`code`, `name`) VALUES ('GTM', 'Guatemala');
INSERT INTO `countries` (`code`, `name`) VALUES ('GUI', 'Guinea');
INSERT INTO `countries` (`code`, `name`) VALUES ('GBI', 'Guinea-Bissau');
INSERT INTO `countries` (`code`, `name`) VALUES ('EGU', 'Equatorial Guinea');
INSERT INTO `countries` (`code`, `name`) VALUES ('GUY', 'Guyana');
INSERT INTO `countries` (`code`, `name`) VALUES ('HAI', 'Haiti');
INSERT INTO `countries` (`code`, `name`) VALUES ('HON', 'Honduras');
INSERT INTO `countries` (`code`, `name`) VALUES ('HKC', 'Hong-Kong, China');
INSERT INTO `countries` (`code`, `name`) VALUES ('HUN', 'Hungary');
INSERT INTO `countries` (`code`, `name`) VALUES ('IND', 'India');
INSERT INTO `countries` (`code`, `name`) VALUES ('IDN', 'Indonesia');
INSERT INTO `countries` (`code`, `name`) VALUES ('IRI', 'Islamic Republic Of Iran');
INSERT INTO `countries` (`code`, `name`) VALUES ('IRA', 'Iraq');
INSERT INTO `countries` (`code`, `name`) VALUES ('IRE', 'Ireland');
INSERT INTO `countries` (`code`, `name`) VALUES ('ICE', 'Iceland');
INSERT INTO `countries` (`code`, `name`) VALUES ('ISR', 'Israel');
INSERT INTO `countries` (`code`, `name`) VALUES ('ITA', 'Italy');
INSERT INTO `countries` (`code`, `name`) VALUES ('JAM', 'Jamaica');
INSERT INTO `countries` (`code`, `name`) VALUES ('JPN', 'Japan');
INSERT INTO `countries` (`code`, `name`) VALUES ('JDN', 'Jordan');
INSERT INTO `countries` (`code`, `name`) VALUES ('KAZ', 'Kazakhstan');
INSERT INTO `countries` (`code`, `name`) VALUES ('KNY', 'Kenya');
INSERT INTO `countries` (`code`, `name`) VALUES ('KYR', 'Kyrgyzstan');
INSERT INTO `countries` (`code`, `name`) VALUES ('KIR', 'Kiribati');
INSERT INTO `countries` (`code`, `name`) VALUES ('KOS', 'Kosovo');
INSERT INTO `countries` (`code`, `name`) VALUES ('KUW', 'Kuwait');
INSERT INTO `countries` (`code`, `name`) VALUES ('LPD', 'Lao People`s Democratic Republic');
INSERT INTO `countries` (`code`, `name`) VALUES ('LES', 'Lesotho');
INSERT INTO `countries` (`code`, `name`) VALUES ('LAT', 'Latvia');
INSERT INTO `countries` (`code`, `name`) VALUES ('LBN', 'Lebanon');
INSERT INTO `countries` (`code`, `name`) VALUES ('LBR', 'Liberia');
INSERT INTO `countries` (`code`, `name`) VALUES ('LIB', 'Libya');
INSERT INTO `countries` (`code`, `name`) VALUES ('LIE', 'Liechtenstein');
INSERT INTO `countries` (`code`, `name`) VALUES ('LTH', 'Lithuania');
INSERT INTO `countries` (`code`, `name`) VALUES ('LXB', 'Luxembourg');
INSERT INTO `countries` (`code`, `name`) VALUES ('MDC', 'Madagascar');
INSERT INTO `countries` (`code`, `name`) VALUES ('MLS', 'Malaysia');
INSERT INTO `countries` (`code`, `name`) VALUES ('MWI', 'Malawi');
INSERT INTO `countries` (`code`, `name`) VALUES ('MDV', 'Maldives');
INSERT INTO `countries` (`code`, `name`) VALUES ('MAL', 'Mali');
INSERT INTO `countries` (`code`, `name`) VALUES ('MLT', 'Malta');
INSERT INTO `countries` (`code`, `name`) VALUES ('MOR', 'Morocco');
INSERT INTO `countries` (`code`, `name`) VALUES ('MSI', 'Marshall Islands');
INSERT INTO `countries` (`code`, `name`) VALUES ('MAU', 'Mauritius');
INSERT INTO `countries` (`code`, `name`) VALUES ('MRT', 'Mauritania');
INSERT INTO `countries` (`code`, `name`) VALUES ('MEX', 'Mexico');
INSERT INTO `countries` (`code`, `name`) VALUES ('FSM', 'Federated States Of Micronesia');
INSERT INTO `countries` (`code`, `name`) VALUES ('ROM', 'Republic Of Moldova');
INSERT INTO `countries` (`code`, `name`) VALUES ('MON', 'Monaco');
INSERT INTO `countries` (`code`, `name`) VALUES ('MGL', 'Mongolia');
INSERT INTO `countries` (`code`, `name`) VALUES ('MTN', 'Montenegro');
INSERT INTO `countries` (`code`, `name`) VALUES ('MZB', 'Mozambique');
INSERT INTO `countries` (`code`, `name`) VALUES ('MYM', 'Myanmar');
INSERT INTO `countries` (`code`, `name`) VALUES ('NMB', 'Namibia');
INSERT INTO `countries` (`code`, `name`) VALUES ('NAU', 'Nauru');
INSERT INTO `countries` (`code`, `name`) VALUES ('NEP', 'Nepal');
INSERT INTO `countries` (`code`, `name`) VALUES ('NIC', 'Nicaragua');
INSERT INTO `countries` (`code`, `name`) VALUES ('NGR', 'Niger');
INSERT INTO `countries` (`code`, `name`) VALUES ('NIG', 'Nigeria');
INSERT INTO `countries` (`code`, `name`) VALUES ('MWY', 'Norway');
INSERT INTO `countries` (`code`, `name`) VALUES ('NZL', 'New Zealand');
INSERT INTO `countries` (`code`, `name`) VALUES ('OMN', 'Oman');
INSERT INTO `countries` (`code`, `name`) VALUES ('UGA', 'Uganda');
INSERT INTO `countries` (`code`, `name`) VALUES ('UZB', 'Uzbekistan');
INSERT INTO `countries` (`code`, `name`) VALUES ('PKT', 'Pakistan');
INSERT INTO `countries` (`code`, `name`) VALUES ('PAL', 'Palau');
INSERT INTO `countries` (`code`, `name`) VALUES ('PLT', 'Palestine');
INSERT INTO `countries` (`code`, `name`) VALUES ('PNM', 'Panama');
INSERT INTO `countries` (`code`, `name`) VALUES ('PNG', 'Papua New Guinea');
INSERT INTO `countries` (`code`, `name`) VALUES ('PAR', 'Paraguay');
INSERT INTO `countries` (`code`, `name`) VALUES ('NTL', 'Netherlands');
INSERT INTO `countries` (`code`, `name`) VALUES ('PER', 'Peru');
INSERT INTO `countries` (`code`, `name`) VALUES ('PHI', 'Philippines');
INSERT INTO `countries` (`code`, `name`) VALUES ('PLD', 'Poland');
INSERT INTO `countries` (`code`, `name`) VALUES ('PUR', 'Puerto Rico');
INSERT INTO `countries` (`code`, `name`) VALUES ('POR', 'Portugal');
INSERT INTO `countries` (`code`, `name`) VALUES ('QTR', 'Qatar');
INSERT INTO `countries` (`code`, `name`) VALUES ('DPK', 'Democratic People`s Republic Of Korea');
INSERT INTO `countries` (`code`, `name`) VALUES ('RMN', 'Romania');
INSERT INTO `countries` (`code`, `name`) VALUES ('RSF', 'Russian Federation');
INSERT INTO `countries` (`code`, `name`) VALUES ('RWA', 'Rwanda');
INSERT INTO `countries` (`code`, `name`) VALUES ('SKN', 'Saint Kitts And Nevis');
INSERT INTO `countries` (`code`, `name`) VALUES ('SLC', 'Saint Lucia');
INSERT INTO `countries` (`code`, `name`) VALUES ('SMA', 'San Marino');
INSERT INTO `countries` (`code`, `name`) VALUES ('VGR', 'St Vincent And The Grenadines');
INSERT INTO `countries` (`code`, `name`) VALUES ('SIS', 'Solomon Islands');
INSERT INTO `countries` (`code`, `name`) VALUES ('SAM', 'Samoa (Until 1996 Western Samoa)');
INSERT INTO `countries` (`code`, `name`) VALUES ('ASA', 'American Samoa');
INSERT INTO `countries` (`code`, `name`) VALUES ('STP', 'Sao Tome And Principe');
INSERT INTO `countries` (`code`, `name`) VALUES ('SEN', 'Senegal');
INSERT INTO `countries` (`code`, `name`) VALUES ('SER', 'Serbia');
INSERT INTO `countries` (`code`, `name`) VALUES ('SEY', 'Seychelles');
INSERT INTO `countries` (`code`, `name`) VALUES ('SLE', 'Sierra Leone');
INSERT INTO `countries` (`code`, `name`) VALUES ('SIN', 'Singapore');
INSERT INTO `countries` (`code`, `name`) VALUES ('SLV', 'Slovakia');
INSERT INTO `countries` (`code`, `name`) VALUES ('SLN', 'Slovenia');
INSERT INTO `countries` (`code`, `name`) VALUES ('SML', 'Somalia');
INSERT INTO `countries` (`code`, `name`) VALUES ('SSD', 'South Sudan');
INSERT INTO `countries` (`code`, `name`) VALUES ('SDN', 'Sudan');
INSERT INTO `countries` (`code`, `name`) VALUES ('SLK', 'Sri Lanka');
INSERT INTO `countries` (`code`, `name`) VALUES ('SWD', 'Sweden');
INSERT INTO `countries` (`code`, `name`) VALUES ('SWT', 'Switzerland');
INSERT INTO `countries` (`code`, `name`) VALUES ('SRN', 'Suriname');
INSERT INTO `countries` (`code`, `name`) VALUES ('SWA', 'Swaziland');
INSERT INTO `countries` (`code`, `name`) VALUES ('SYR', 'Syrian Arab Republic');
INSERT INTO `countries` (`code`, `name`) VALUES ('TAJ', 'Tajikistan');
INSERT INTO `countries` (`code`, `name`) VALUES ('CNT', 'Chinese Taipei');
INSERT INTO `countries` (`code`, `name`) VALUES ('URT', 'United Republic Of Tanzania');
INSERT INTO `countries` (`code`, `name`) VALUES ('CHD', 'Chad');
INSERT INTO `countries` (`code`, `name`) VALUES ('CZR', 'Czech Republic');
INSERT INTO `countries` (`code`, `name`) VALUES ('TLD', 'Thailand');
INSERT INTO `countries` (`code`, `name`) VALUES ('TLE', 'Timor-Leste');
INSERT INTO `countries` (`code`, `name`) VALUES ('TOG', 'Togo');
INSERT INTO `countries` (`code`, `name`) VALUES ('TON', 'Tonga');
INSERT INTO `countries` (`code`, `name`) VALUES ('TAT', 'Trinidad And Tobago');
INSERT INTO `countries` (`code`, `name`) VALUES ('TUN', 'Tunisia');
INSERT INTO `countries` (`code`, `name`) VALUES ('TUR', 'Turkmenistan');
INSERT INTO `countries` (`code`, `name`) VALUES ('TKY', 'Turkey');
INSERT INTO `countries` (`code`, `name`) VALUES ('TUV', 'Tuvalu');
INSERT INTO `countries` (`code`, `name`) VALUES ('UKR', 'Ukraine');
INSERT INTO `countries` (`code`, `name`) VALUES ('URU', 'Uruguay');
INSERT INTO `countries` (`code`, `name`) VALUES ('VAN', 'Vanuatu');
INSERT INTO `countries` (`code`, `name`) VALUES ('VEN', 'Venezuela');
INSERT INTO `countries` (`code`, `name`) VALUES ('VIB', 'Virgin Islands, British');
INSERT INTO `countries` (`code`, `name`) VALUES ('VIS', 'Virgin Islands, US');
INSERT INTO `countries` (`code`, `name`) VALUES ('VIE', 'Vietnam');
INSERT INTO `countries` (`code`, `name`) VALUES ('YEM', 'Yemen');
INSERT INTO `countries` (`code`, `name`) VALUES ('ZAM', 'Zambia');
INSERT INTO `countries` (`code`, `name`) VALUES ('ZIM', 'Zimbabwe');


-- insert locals
INSERT INTO `locals` (`name`) VALUES ('Olympic Stadium');
INSERT INTO `locals` (`name`) VALUES ('Yoyogi National Gymnasium');
INSERT INTO `locals` (`name`) VALUES ('Tokyo Metropolitan Gymnasium');
INSERT INTO `locals` (`name`) VALUES ('Nippon Budokan');
INSERT INTO `locals` (`name`) VALUES ('Tokyo International Forum');
INSERT INTO `locals` (`name`) VALUES ('Imperial Palace Garden');
INSERT INTO `locals` (`name`) VALUES ('Kokugikan Arena');


-- insert modalities
INSERT INTO `modalities` (`name`) VALUES ('Archery');
INSERT INTO `modalities` (`name`) VALUES ('Athletics');
INSERT INTO `modalities` (`name`) VALUES ('Badminton');
INSERT INTO `modalities` (`name`) VALUES ('Basketball');
INSERT INTO `modalities` (`name`) VALUES ('Beach Volleyball');
INSERT INTO `modalities` (`name`) VALUES ('Boxing');
INSERT INTO `modalities` (`name`) VALUES ('Canoe Slalom');
INSERT INTO `modalities` (`name`) VALUES ('Canoe Sprint');
INSERT INTO `modalities` (`name`) VALUES ('Cycling Bmx');
INSERT INTO `modalities` (`name`) VALUES ('Cycling Mountain Bike');
INSERT INTO `modalities` (`name`) VALUES ('Cycling Road');
INSERT INTO `modalities` (`name`) VALUES ('Cycling Track');
INSERT INTO `modalities` (`name`) VALUES ('Diving');
INSERT INTO `modalities` (`name`) VALUES ('Equestrian/Dressage');
INSERT INTO `modalities` (`name`) VALUES ('Equestrian/Eventing');
INSERT INTO `modalities` (`name`) VALUES ('Equestrian/Jumping');
INSERT INTO `modalities` (`name`) VALUES ('Fencing');
INSERT INTO `modalities` (`name`) VALUES ('Football');
INSERT INTO `modalities` (`name`) VALUES ('Golf');
INSERT INTO `modalities` (`name`) VALUES ('Gymnastics Artistic');
INSERT INTO `modalities` (`name`) VALUES ('Gymnastics Rhythmic');
INSERT INTO `modalities` (`name`) VALUES ('Handball');
INSERT INTO `modalities` (`name`) VALUES ('Hockey');
INSERT INTO `modalities` (`name`) VALUES ('Judo');
INSERT INTO `modalities` (`name`) VALUES ('Modern Pentathlon');
INSERT INTO `modalities` (`name`) VALUES ('Rowing');
INSERT INTO `modalities` (`name`) VALUES ('Rugby');
INSERT INTO `modalities` (`name`) VALUES ('Sailing');
INSERT INTO `modalities` (`name`) VALUES ('Shooting');
INSERT INTO `modalities` (`name`) VALUES ('Swimming');
INSERT INTO `modalities` (`name`) VALUES ('Synchronized Swimming');
INSERT INTO `modalities` (`name`) VALUES ('Table Tennis');
INSERT INTO `modalities` (`name`) VALUES ('Taekwondo');
INSERT INTO `modalities` (`name`) VALUES ('Tennis');
INSERT INTO `modalities` (`name`) VALUES ('Trampoline');
INSERT INTO `modalities` (`name`) VALUES ('Triathlon');
INSERT INTO `modalities` (`name`) VALUES ('Volleyball');
INSERT INTO `modalities` (`name`) VALUES ('Water Polo');
INSERT INTO `modalities` (`name`) VALUES ('Weightlifting');
INSERT INTO `modalities` (`name`) VALUES ('Wrestling Freestyle');
INSERT INTO `modalities` (`name`) VALUES ('Wrestling Greco-Roman');

